// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getHandleByDatumCode.proto

package com.sunsheen.metadatacom.grpc.service.handle;

public final class HandleProto {
  private HandleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032getHandleByDatumCode.proto\022\006handle\032\020gr" +
      "pcCommon.proto2a\n\rHandleService\022P\n\024getHa" +
      "ndleByDatumCode\022\034.grpccommon.DatumCodeRe" +
      "quest\032\030.grpccommon.ResponseData\"\000B=\n,com" +
      ".sunsheen.metadatacom.grpc.service.handl" +
      "eB\013HandleProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor(),
        }, assigner);
    com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
