# grpc client config
server:
  port: 8888
  servlet:
    # 项目contextPath
    context-path: /metadata
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30

spring:
  application:
    name: local-grpc-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mmd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  kafka:
#    # Kafka服务端的主机名和端口号
#    bootstrap-servers: Linux01:9092,Linux02:9092,Linux03:9092
#    # Provider
#    producer:
#      # 等待所有副本节点的应答后再发送
#      acks: all
#      # 如果该值大于零时，表示启用重试失败的发送次数
#      retries: 0
#      # 一批消息处理大小
#      batch-size: 16384
#      # 发送缓存区内存大小
#      buffer-memory: 33554432
#      # 配置key和value的序列化
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    # Consumer
#    consumer:
#      # 制定consumer group
#      group-id: test
#      # 如果为true，则消费者的偏移量将在后台定期提交，默认值为true（是否自动确认offset）
#      enable-auto-commit: true
#      # 如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000（自动确认offset的时间间隔）
#      auto-commit-interval: 1000
#      # 密钥的反序列化器类
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      # 值的反序列化器类
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

grpc:
  server:
    port: 9898

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.sunsheen
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
