// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getDatumtypehyp.proto

package com.sunsheen.metadatacom.grpc.service.datumtypehyp;

public final class DatumtypehypProto {
  private DatumtypehypProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025getDatumtypehyp.proto\022\014datumtypehyp\032\020g" +
      "rpcCommon.proto2`\n\023DatumtypehypService\022I" +
      "\n\017getDatumtypehyp\022\032.grpccommon.UserPwdRe" +
      "quest\032\030.grpccommon.ResponseData\"\000BI\n2com" +
      ".sunsheen.metadatacom.grpc.service.datum" +
      "typehypB\021DatumtypehypProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor(),
        }, assigner);
    com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
