// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getDatumtypeelm.proto

package com.sunsheen.metadatacom.grpc.service.datumtypeelm;

public final class DatumtypeelmProto {
  private DatumtypeelmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025getDatumtypeelm.proto\022\014datumtypeelm\032\020g" +
      "rpcCommon.proto2\270\001\n\023DatumtypeelmService\022" +
      "I\n\017getDatumtypeelm\022\032.grpccommon.UserPwdR" +
      "equest\032\030.grpccommon.ResponseData\"\000\022V\n\032ge" +
      "tElementsInfoByDatumCode\022\034.grpccommon.Da" +
      "tumCodeRequest\032\030.grpccommon.ResponseData" +
      "\"\000BI\n2com.sunsheen.metadatacom.grpc.serv" +
      "ice.datumtypeelmB\021DatumtypeelmProtoP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor(),
        }, assigner);
    com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
