# grpc client config
server:
  port: 9090
  servlet:
    # 项目contextPath
    context-path: /metadataClient
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30
spring:
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpc-server:
      host: 127.0.0.1
      port: 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      maxInboundMessageSize: 30000000