// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

/**
 * <pre>
 * 请求参数，用户信息校验条件和资料编码条件
 * </pre>
 *
 * Protobuf type {@code grpccommon.DatumCodeRequest}
 */
public  final class DatumCodeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpccommon.DatumCodeRequest)
    DatumCodeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DatumCodeRequest.newBuilder() to construct.
  private DatumCodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DatumCodeRequest() {
    datumCode_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DatumCodeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.Builder subBuilder = null;
            if (userPwdRequest_ != null) {
              subBuilder = userPwdRequest_.toBuilder();
            }
            userPwdRequest_ = input.readMessage(com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userPwdRequest_);
              userPwdRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            datumCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_DatumCodeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_DatumCodeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.class, com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.Builder.class);
  }

  public static final int USERPWDREQUEST_FIELD_NUMBER = 1;
  private com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest userPwdRequest_;
  /**
   * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
   */
  public boolean hasUserPwdRequest() {
    return userPwdRequest_ != null;
  }
  /**
   * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
   */
  public com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest getUserPwdRequest() {
    return userPwdRequest_ == null ? com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.getDefaultInstance() : userPwdRequest_;
  }
  /**
   * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
   */
  public com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequestOrBuilder getUserPwdRequestOrBuilder() {
    return getUserPwdRequest();
  }

  public static final int DATUMCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object datumCode_;
  /**
   * <code>string datumCode = 2;</code>
   */
  public java.lang.String getDatumCode() {
    java.lang.Object ref = datumCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datumCode_ = s;
      return s;
    }
  }
  /**
   * <code>string datumCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDatumCodeBytes() {
    java.lang.Object ref = datumCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datumCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userPwdRequest_ != null) {
      output.writeMessage(1, getUserPwdRequest());
    }
    if (!getDatumCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datumCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userPwdRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserPwdRequest());
    }
    if (!getDatumCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datumCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest)) {
      return super.equals(obj);
    }
    com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest other = (com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest) obj;

    boolean result = true;
    result = result && (hasUserPwdRequest() == other.hasUserPwdRequest());
    if (hasUserPwdRequest()) {
      result = result && getUserPwdRequest()
          .equals(other.getUserPwdRequest());
    }
    result = result && getDatumCode()
        .equals(other.getDatumCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserPwdRequest()) {
      hash = (37 * hash) + USERPWDREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getUserPwdRequest().hashCode();
    }
    hash = (37 * hash) + DATUMCODE_FIELD_NUMBER;
    hash = (53 * hash) + getDatumCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 请求参数，用户信息校验条件和资料编码条件
   * </pre>
   *
   * Protobuf type {@code grpccommon.DatumCodeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpccommon.DatumCodeRequest)
      com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_DatumCodeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_DatumCodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.class, com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.Builder.class);
    }

    // Construct using com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userPwdRequestBuilder_ == null) {
        userPwdRequest_ = null;
      } else {
        userPwdRequest_ = null;
        userPwdRequestBuilder_ = null;
      }
      datumCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_DatumCodeRequest_descriptor;
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest getDefaultInstanceForType() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest build() {
      com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest buildPartial() {
      com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest result = new com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest(this);
      if (userPwdRequestBuilder_ == null) {
        result.userPwdRequest_ = userPwdRequest_;
      } else {
        result.userPwdRequest_ = userPwdRequestBuilder_.build();
      }
      result.datumCode_ = datumCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest) {
        return mergeFrom((com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest other) {
      if (other == com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest.getDefaultInstance()) return this;
      if (other.hasUserPwdRequest()) {
        mergeUserPwdRequest(other.getUserPwdRequest());
      }
      if (!other.getDatumCode().isEmpty()) {
        datumCode_ = other.datumCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest userPwdRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest, com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.Builder, com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequestOrBuilder> userPwdRequestBuilder_;
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public boolean hasUserPwdRequest() {
      return userPwdRequestBuilder_ != null || userPwdRequest_ != null;
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest getUserPwdRequest() {
      if (userPwdRequestBuilder_ == null) {
        return userPwdRequest_ == null ? com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.getDefaultInstance() : userPwdRequest_;
      } else {
        return userPwdRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public Builder setUserPwdRequest(com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest value) {
      if (userPwdRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userPwdRequest_ = value;
        onChanged();
      } else {
        userPwdRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public Builder setUserPwdRequest(
        com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.Builder builderForValue) {
      if (userPwdRequestBuilder_ == null) {
        userPwdRequest_ = builderForValue.build();
        onChanged();
      } else {
        userPwdRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public Builder mergeUserPwdRequest(com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest value) {
      if (userPwdRequestBuilder_ == null) {
        if (userPwdRequest_ != null) {
          userPwdRequest_ =
            com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.newBuilder(userPwdRequest_).mergeFrom(value).buildPartial();
        } else {
          userPwdRequest_ = value;
        }
        onChanged();
      } else {
        userPwdRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public Builder clearUserPwdRequest() {
      if (userPwdRequestBuilder_ == null) {
        userPwdRequest_ = null;
        onChanged();
      } else {
        userPwdRequest_ = null;
        userPwdRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.Builder getUserPwdRequestBuilder() {
      
      onChanged();
      return getUserPwdRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    public com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequestOrBuilder getUserPwdRequestOrBuilder() {
      if (userPwdRequestBuilder_ != null) {
        return userPwdRequestBuilder_.getMessageOrBuilder();
      } else {
        return userPwdRequest_ == null ?
            com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.getDefaultInstance() : userPwdRequest_;
      }
    }
    /**
     * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest, com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.Builder, com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequestOrBuilder> 
        getUserPwdRequestFieldBuilder() {
      if (userPwdRequestBuilder_ == null) {
        userPwdRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest, com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest.Builder, com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequestOrBuilder>(
                getUserPwdRequest(),
                getParentForChildren(),
                isClean());
        userPwdRequest_ = null;
      }
      return userPwdRequestBuilder_;
    }

    private java.lang.Object datumCode_ = "";
    /**
     * <code>string datumCode = 2;</code>
     */
    public java.lang.String getDatumCode() {
      java.lang.Object ref = datumCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datumCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string datumCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDatumCodeBytes() {
      java.lang.Object ref = datumCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datumCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datumCode = 2;</code>
     */
    public Builder setDatumCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datumCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string datumCode = 2;</code>
     */
    public Builder clearDatumCode() {
      
      datumCode_ = getDefaultInstance().getDatumCode();
      onChanged();
      return this;
    }
    /**
     * <code>string datumCode = 2;</code>
     */
    public Builder setDatumCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datumCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpccommon.DatumCodeRequest)
  }

  // @@protoc_insertion_point(class_scope:grpccommon.DatumCodeRequest)
  private static final com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest();
  }

  public static com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DatumCodeRequest>
      PARSER = new com.google.protobuf.AbstractParser<DatumCodeRequest>() {
    @java.lang.Override
    public DatumCodeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DatumCodeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DatumCodeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DatumCodeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sunsheen.metadatacom.grpc.service.grpccommon.DatumCodeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

