// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface DatumCodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.DatumCodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
   */
  boolean hasUserPwdRequest();
  /**
   * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
   */
  com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequest getUserPwdRequest();
  /**
   * <code>.grpccommon.UserPwdRequest userPwdRequest = 1;</code>
   */
  com.sunsheen.metadatacom.grpc.service.grpccommon.UserPwdRequestOrBuilder getUserPwdRequestOrBuilder();

  /**
   * <code>string datumCode = 2;</code>
   */
  java.lang.String getDatumCode();
  /**
   * <code>string datumCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatumCodeBytes();
}
