// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface DbDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.DbData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .grpccommon.TableMap tableMap = 1;</code>
   */
  java.util.List<com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap> 
      getTableMapList();
  /**
   * <code>repeated .grpccommon.TableMap tableMap = 1;</code>
   */
  com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap getTableMap(int index);
  /**
   * <code>repeated .grpccommon.TableMap tableMap = 1;</code>
   */
  int getTableMapCount();
  /**
   * <code>repeated .grpccommon.TableMap tableMap = 1;</code>
   */
  java.util.List<? extends com.sunsheen.metadatacom.grpc.service.grpccommon.TableMapOrBuilder> 
      getTableMapOrBuilderList();
  /**
   * <code>repeated .grpccommon.TableMap tableMap = 1;</code>
   */
  com.sunsheen.metadatacom.grpc.service.grpccommon.TableMapOrBuilder getTableMapOrBuilder(
      int index);
}
