// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface IntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.IntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intValue = 1;</code>
   */
  int getIntValue();
}
