// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

/**
 * <pre>
 * long类型字段
 * </pre>
 *
 * Protobuf type {@code grpccommon.LongResponse}
 */
public  final class LongResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpccommon.LongResponse)
    LongResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LongResponse.newBuilder() to construct.
  private LongResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LongResponse() {
    longValue_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LongResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            longValue_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_LongResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_LongResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.class, com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.Builder.class);
  }

  public static final int LONGVALUE_FIELD_NUMBER = 1;
  private long longValue_;
  /**
   * <code>int64 longValue = 1;</code>
   */
  public long getLongValue() {
    return longValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (longValue_ != 0L) {
      output.writeInt64(1, longValue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (longValue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, longValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse)) {
      return super.equals(obj);
    }
    com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse other = (com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse) obj;

    boolean result = true;
    result = result && (getLongValue()
        == other.getLongValue());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LONGVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLongValue());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * long类型字段
   * </pre>
   *
   * Protobuf type {@code grpccommon.LongResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpccommon.LongResponse)
      com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_LongResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_LongResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.class, com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.Builder.class);
    }

    // Construct using com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      longValue_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_LongResponse_descriptor;
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse getDefaultInstanceForType() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse build() {
      com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse buildPartial() {
      com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse result = new com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse(this);
      result.longValue_ = longValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse) {
        return mergeFrom((com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse other) {
      if (other == com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse.getDefaultInstance()) return this;
      if (other.getLongValue() != 0L) {
        setLongValue(other.getLongValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long longValue_ ;
    /**
     * <code>int64 longValue = 1;</code>
     */
    public long getLongValue() {
      return longValue_;
    }
    /**
     * <code>int64 longValue = 1;</code>
     */
    public Builder setLongValue(long value) {
      
      longValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 longValue = 1;</code>
     */
    public Builder clearLongValue() {
      
      longValue_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpccommon.LongResponse)
  }

  // @@protoc_insertion_point(class_scope:grpccommon.LongResponse)
  private static final com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse();
  }

  public static com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LongResponse>
      PARSER = new com.google.protobuf.AbstractParser<LongResponse>() {
    @java.lang.Override
    public LongResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LongResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LongResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LongResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sunsheen.metadatacom.grpc.service.grpccommon.LongResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

