// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface LongResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.LongResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 longValue = 1;</code>
   */
  long getLongValue();
}
