// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface ResponseDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.ResponseData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回状态
   * </pre>
   *
   * <code>int32 returnCode = 1;</code>
   */
  int getReturnCode();

  /**
   * <pre>
   * 返回数据
   * </pre>
   *
   * <code>.grpccommon.DbData dbData = 2;</code>
   */
  boolean hasDbData();
  /**
   * <pre>
   * 返回数据
   * </pre>
   *
   * <code>.grpccommon.DbData dbData = 2;</code>
   */
  com.sunsheen.metadatacom.grpc.service.grpccommon.DbData getDbData();
  /**
   * <pre>
   * 返回数据
   * </pre>
   *
   * <code>.grpccommon.DbData dbData = 2;</code>
   */
  com.sunsheen.metadatacom.grpc.service.grpccommon.DbDataOrBuilder getDbDataOrBuilder();
}
