// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringValue = 1;</code>
   */
  java.lang.String getStringValue();
  /**
   * <code>string stringValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();
}
