// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

/**
 * <pre>
 * 2.响应的消息类型
 * 返回数据库数据
 * </pre>
 *
 * Protobuf type {@code grpccommon.TableMap}
 */
public  final class TableMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpccommon.TableMap)
    TableMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TableMap.newBuilder() to construct.
  private TableMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TableMap() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TableMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              mapAny_ = com.google.protobuf.MapField.newMapField(
                  MapAnyDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
            mapAny__ = input.readMessage(
                MapAnyDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            mapAny_.getMutableMap().put(
                mapAny__.getKey(), mapAny__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_TableMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetMapAny();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_TableMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.class, com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.Builder.class);
  }

  public static final int MAPANY_FIELD_NUMBER = 1;
  private static final class MapAnyDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.Any> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_TableMap_MapAnyEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.protobuf.Any.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.Any> mapAny_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
  internalGetMapAny() {
    if (mapAny_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapAnyDefaultEntryHolder.defaultEntry);
    }
    return mapAny_;
  }

  public int getMapAnyCount() {
    return internalGetMapAny().getMap().size();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */

  public boolean containsMapAny(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMapAny().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapAnyMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.Any> getMapAny() {
    return getMapAnyMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.Any> getMapAnyMap() {
    return internalGetMapAny().getMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */

  public com.google.protobuf.Any getMapAnyOrDefault(
      java.lang.String key,
      com.google.protobuf.Any defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.Any> map =
        internalGetMapAny().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */

  public com.google.protobuf.Any getMapAnyOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.Any> map =
        internalGetMapAny().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMapAny(),
        MapAnyDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
         : internalGetMapAny().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
      mapAny__ = MapAnyDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mapAny__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap)) {
      return super.equals(obj);
    }
    com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap other = (com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap) obj;

    boolean result = true;
    result = result && internalGetMapAny().equals(
        other.internalGetMapAny());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetMapAny().getMap().isEmpty()) {
      hash = (37 * hash) + MAPANY_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMapAny().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 2.响应的消息类型
   * 返回数据库数据
   * </pre>
   *
   * Protobuf type {@code grpccommon.TableMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpccommon.TableMap)
      com.sunsheen.metadatacom.grpc.service.grpccommon.TableMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_TableMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMapAny();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableMapAny();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_TableMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.class, com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.Builder.class);
    }

    // Construct using com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableMapAny().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.internal_static_grpccommon_TableMap_descriptor;
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap getDefaultInstanceForType() {
      return com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.getDefaultInstance();
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap build() {
      com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap buildPartial() {
      com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap result = new com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap(this);
      int from_bitField0_ = bitField0_;
      result.mapAny_ = internalGetMapAny();
      result.mapAny_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap) {
        return mergeFrom((com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap other) {
      if (other == com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap.getDefaultInstance()) return this;
      internalGetMutableMapAny().mergeFrom(
          other.internalGetMapAny());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> mapAny_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetMapAny() {
      if (mapAny_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapAnyDefaultEntryHolder.defaultEntry);
      }
      return mapAny_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetMutableMapAny() {
      onChanged();;
      if (mapAny_ == null) {
        mapAny_ = com.google.protobuf.MapField.newMapField(
            MapAnyDefaultEntryHolder.defaultEntry);
      }
      if (!mapAny_.isMutable()) {
        mapAny_ = mapAny_.copy();
      }
      return mapAny_;
    }

    public int getMapAnyCount() {
      return internalGetMapAny().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */

    public boolean containsMapAny(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMapAny().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapAnyMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getMapAny() {
      return getMapAnyMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.Any> getMapAnyMap() {
      return internalGetMapAny().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */

    public com.google.protobuf.Any getMapAnyOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetMapAny().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */

    public com.google.protobuf.Any getMapAnyOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetMapAny().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMapAny() {
      internalGetMutableMapAny().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */

    public Builder removeMapAny(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMapAny().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any>
    getMutableMapAny() {
      return internalGetMutableMapAny().getMutableMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */
    public Builder putMapAny(
        java.lang.String key,
        com.google.protobuf.Any value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMapAny().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
     */

    public Builder putAllMapAny(
        java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
      internalGetMutableMapAny().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpccommon.TableMap)
  }

  // @@protoc_insertion_point(class_scope:grpccommon.TableMap)
  private static final com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap();
  }

  public static com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TableMap>
      PARSER = new com.google.protobuf.AbstractParser<TableMap>() {
    @java.lang.Override
    public TableMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TableMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TableMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TableMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sunsheen.metadatacom.grpc.service.grpccommon.TableMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

