// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface TableMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.TableMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */
  int getMapAnyCount();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */
  boolean containsMapAny(
      java.lang.String key);
  /**
   * Use {@link #getMapAnyMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Any>
  getMapAny();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Any>
  getMapAnyMap();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */

  com.google.protobuf.Any getMapAnyOrDefault(
      java.lang.String key,
      com.google.protobuf.Any defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; mapAny = 1;</code>
   */

  com.google.protobuf.Any getMapAnyOrThrow(
      java.lang.String key);
}
