// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommon.proto

package com.sunsheen.metadatacom.grpc.service.grpccommon;

public interface UserPwdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpccommon.UserPwdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string pwd = 2;</code>
   */
  java.lang.String getPwd();
  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string pwd = 2;</code>
   */
  com.google.protobuf.ByteString
      getPwdBytes();

  /**
   * <pre>
   * 接口url
   * </pre>
   *
   * <code>string interfaceId = 3;</code>
   */
  java.lang.String getInterfaceId();
  /**
   * <pre>
   * 接口url
   * </pre>
   *
   * <code>string interfaceId = 3;</code>
   */
  com.google.protobuf.ByteString
      getInterfaceIdBytes();
}
