// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getElement.proto

package com.sunsheen.metadatacom.grpc.service.element;

public final class ElementProto {
  private ElementProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020getElement.proto\022\007element\032\020grpcCommon." +
      "proto2V\n\016ElementService\022D\n\ngetElement\022\032." +
      "grpccommon.UserPwdRequest\032\030.grpccommon.R" +
      "esponseData\"\000B?\n-com.sunsheen.metadataco" +
      "m.grpc.service.elementB\014ElementProtoP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor(),
        }, assigner);
    com.sunsheen.metadatacom.grpc.service.grpccommon.GrpcCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
